import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { AlertTriangle, Bot, ClipboardList, MapPin, RefreshCw, RotateCcw, ShieldCheck, Siren, Users, CheckCircle2, XCircle } from "lucide-react";
import API from "../utils/api";
import { useToast } from "../contexts/ToastContext.jsx";
import Surface from "../components/ui/Surface.jsx";
import Button from "../components/ui/Button.jsx";
import EmptyState from "../components/ui/EmptyState.jsx";
import { CaseListSkeleton } from "../components/ui/LoadingState.jsx";
import { StatusBadge, PriorityBadge } from "../components/ui/Badge.jsx";

export default function AdminWorkspace(){
 const location=useLocation(); const { showToast } = useToast(); const [cases,setCases]=useState([]); const [junk,setJunk]=useState([]); const [accounts,setAccounts]=useState([]); const [loading,setLoading]=useState(true); const [accountLoading,setAccountLoading]=useState(false); const [acting,setActing]=useState(null); const [error,setError]=useState(""); const view=location.pathname.split("/")[2]||"control";
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [c,j]=await Promise.all([API.get("/cases"),API.get("/cases/admin/junk")]);setCases(Array.isArray(c.data)?c.data:[]);setJunk(Array.isArray(j.data)?j.data:[]);}catch(e){setError(e.response?.data?.error||"Unable to load administrative rescue data.");showToast(e.response?.data?.error||"Unable to load administrative rescue data.","error");}finally{setLoading(false);}},[showToast]);
 useEffect(()=>{load();},[load]);
 const loadAccounts=useCallback(async()=>{setAccountLoading(true);try{const response=await API.get("/admin/users",{params:{status:"PENDING"}});setAccounts(Array.isArray(response.data?.users)?response.data.users:[]);}catch(e){showToast(e.response?.data?.error||"Unable to load pending accounts.","error");}finally{setAccountLoading(false);}},[showToast]);
 useEffect(()=>{if(view==="accounts") loadAccounts();},[view,loadAccounts]);
 const updateAccount=async(id,status)=>{setActing(id);try{await API.put("/admin/users/"+id+"/status",{status});showToast(status==="ACTIVE"?"Account approved.":"Account rejected.","success");await loadAccounts();}catch(e){showToast(e.response?.data?.error||"Unable to update account.","error");}finally{setActing(null);}};
 const counts=useMemo(()=>({total:cases.length,ai:cases.filter(c=>["PENDING_VALIDATION","PROCESSING_ANALYSIS"].includes(c.status)).length,available:cases.filter(c=>c.status==="VALIDATION_PASSED"&&!c.assigned_volunteer_id).length,active:cases.filter(c=>c.status==="IN_PROGRESS").length,resolved:cases.filter(c=>c.status==="RESOLVED").length}),[cases]);
 const verify=async(id)=>{setActing(id);try{await API.put("/cases/"+id+"/verify-junk",{approved:true});showToast("Case marked as valid and returned to the rescue queue.","success");await load();}catch(e){showToast(e.response?.data?.error||"Could not update this AI review.","error");}finally{setActing(null);}};
 const retryAI=async(id)=>{setActing(id);try{await API.put("/cases/"+id+"/retry-ai");showToast("AI validation restarted for this case.","success");await load();}catch(e){showToast(e.response?.data?.error||"Could not restart AI validation.","error");}finally{setActing(null);}};
 if(view==="control") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-stone-900 to-emerald-950 p-6 text-white sm:p-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-300">Administrator · network overview</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Rescue Control Center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-300">See the whole network at a glance. Dedicated workspaces handle cases and AI review.</p></section><section className="mt-8 grid gap-4 lg:grid-cols-5"><AdminPanel Icon={ClipboardList} label="Total cases" value={counts.total} text="Cases across the rescue network." tone="slate"/><AdminPanel Icon={Bot} label="AI review" value={counts.ai} text={junk.length+" case(s) need human attention."} tone="violet"/><AdminPanel Icon={Siren} label="Ready to dispatch" value={counts.available} text="Validated and currently unassigned." tone="amber"/><AdminPanel Icon={AlertTriangle} label="Active rescue" value={counts.active} text="Rescues currently in progress." tone="rose"/><AdminPanel Icon={ShieldCheck} label="Resolved" value={counts.resolved} text="Cases that completed the workflow." tone="emerald"/></section><section className="mt-8 grid gap-4 md:grid-cols-3"><ActionCard icon={<Siren className="text-rose-500"/>} title="Global cases" text="Open the full case inventory for administrative operations." to="/admin/cases"/><ActionCard icon={<Bot className="text-violet-600"/>} title="AI validation" text={junk.length+" flagged case(s) need human review."} to="/admin/ai-validation"/><ActionCard icon={<Users className="text-sky-600"/>} title="Account approvals" text="Review pending volunteer and NGO registrations." to="/admin/accounts"/><ActionCard icon={<ShieldCheck className="text-emerald-600"/>} title="Verification" text="Review completed rescues awaiting sign-off." to="/verification"/></section></main>;
 if(view==="accounts") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><section className="rounded-3xl bg-gradient-to-br from-sky-950 via-slate-950 to-emerald-950 p-6 text-white sm:p-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-sky-300">Administrator · account approvals</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Review registrations</h1><p className="mt-2 max-w-2xl text-sm text-stone-300">Approve or reject pending volunteer and NGO accounts before they can enter the rescue network.</p></section><div className="mt-6">{accountLoading?<CaseListSkeleton/>:accounts.length===0?<Surface className="p-8"><EmptyState icon="✓" title="No pending accounts" message="All volunteer and NGO registrations are currently reviewed."/></Surface>:<div className="grid gap-4 lg:grid-cols-2">{accounts.map(account=><Surface key={account.id} className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-sky-600">{account.role}</p><h2 className="mt-1 text-xl font-black dark:text-white">{account.full_name}</h2><p className="mt-1 text-sm text-stone-500">{account.email}</p>{account.organization_name&&<p className="mt-3 text-sm font-bold text-stone-700 dark:text-stone-300">{account.organization_name}</p>}{account.contact_person&&<p className="mt-1 text-xs text-stone-500">Contact: {account.contact_person}</p>}</div><span className="rounded-full bg-amber-500/10 px-3 py-1 text-xs font-black text-amber-600">PENDING</span></div><div className="mt-5 flex gap-3"><Button disabled={acting===account.id} onClick={()=>updateAccount(account.id,"ACTIVE")} className="flex-1"><CheckCircle2 size={16} className="mr-2"/>Approve</Button><Button disabled={acting===account.id} onClick={()=>updateAccount(account.id,"REJECTED")} variant="secondary" className="flex-1"><XCircle size={16} className="mr-2"/>Reject</Button></div></Surface>)}</div>}</div></main>;
 if(view==="cases") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-rose-600">Global operations</p><h1 className="mt-1 text-3xl font-black dark:text-white">All Rescue Cases</h1><p className="mt-2 text-sm text-stone-500">Global case inventory for administrative operations.</p></div><button onClick={load} className="inline-flex items-center gap-2 text-xs font-bold text-stone-500"><RefreshCw size={14}/> Refresh</button></header>{loading?<CaseListSkeleton/>:error?<Surface className="mt-6 p-8"><EmptyState icon="⚠️" title="Could not load cases" message={error}><Button onClick={load}>Try again</Button></EmptyState></Surface>:<div className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{cases.map(c=><Link key={c.id} to={"/cases/"+c.id} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg dark:border-stone-800 dark:bg-stone-900"><div className="flex justify-between"><p className="text-xs font-black uppercase tracking-wider text-stone-400">Case #{c.id}</p><PriorityBadge priority={c.priority}/></div><h2 className="mt-3 text-lg font-black dark:text-white">{c.species||"Animal rescue"}</h2><p className="mt-1 text-sm text-stone-500">{c.manual_address||c.issue_description||"Location available"}</p><div className="mt-4"><StatusBadge status={c.status} friendly compact/></div></Link>)}</div>}</main>;
 return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><section className="rounded-3xl bg-gradient-to-br from-violet-950 via-slate-950 to-stone-950 p-6 text-white sm:p-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-300">AI operations</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">AI Validation Review</h1><p className="mt-2 max-w-2xl text-sm text-stone-300">Human review of cases the AI validation stage flagged. This workspace is intentionally separate from the global case inventory.</p></section><div className="mt-6">{loading?<CaseListSkeleton/>:error?<Surface className="mt-6 p-8"><EmptyState icon="⚠️" title="Could not load AI review" message={error}><Button onClick={load}>Try again</Button></EmptyState></Surface>:junk.length===0?<Surface className="p-8"><EmptyState icon="🤖" title="AI review queue is clear" message="No AI-flagged cases currently require review."/></Surface>:<div className="grid gap-4 lg:grid-cols-2">{junk.map(c=><Surface key={c.id} className="overflow-hidden border-violet-100 bg-gradient-to-br from-white via-white to-violet-50/60 p-0 shadow-[0_14px_36px_rgba(124,58,237,0.12)] ring-1 ring-violet-100/70 dark:border-violet-950/60 dark:from-stone-900 dark:via-stone-900 dark:to-violet-950/10"><div className="flex items-center justify-between border-b border-violet-100 bg-violet-50/70 px-5 py-4 dark:border-violet-950/60 dark:bg-violet-950/20"><div><p className="text-xs font-black uppercase tracking-wider text-violet-500">Case #{c.id}</p><h2 className="mt-1 text-xl font-black dark:text-white">{c.species||"Reported animal"}</h2></div><div className="grid h-10 w-10 place-items-center rounded-2xl bg-amber-50 text-amber-500 ring-1 ring-amber-100 dark:bg-amber-950/40 dark:ring-amber-900"><AlertTriangle size={18}/></div></div><div className="p-5"><p className="mt-0 text-sm leading-6 text-stone-600 dark:text-stone-300">{c.issue_description||"No description supplied."}</p><p className="mt-3 text-xs text-stone-500"><MapPin size={13} className="mr-1 inline"/> {c.manual_address||"Location available in case detail"}</p><div className="mt-5 flex gap-2"><Button as={Link} to={"/cases/"+c.id} variant="secondary" className="flex-1">Review case</Button><Button disabled={acting===c.id} onClick={()=>verify(c.id)} className="flex-1">{acting===c.id?"Processing...":"Mark as valid"}</Button><Button disabled={acting===c.id} onClick={()=>retryAI(c.id)} variant="secondary" className="flex-1"><RotateCcw size={15} className="mr-2" />Retry AI</Button></div></div></Surface>)}</div>}</div></main>;
}
function AdminPanel({label,value,text,tone,Icon}){const tones={slate:"border-stone-200 bg-gradient-to-br from-white to-stone-100 dark:border-stone-800 dark:from-stone-900 dark:to-stone-800",violet:"border-violet-100 bg-gradient-to-br from-white to-violet-50/70 dark:border-violet-950/60 dark:from-stone-900 dark:to-violet-950/20",amber:"border-amber-100 bg-gradient-to-br from-white to-amber-50/70 dark:border-amber-950/60 dark:from-stone-900 dark:to-amber-950/20",rose:"border-rose-100 bg-gradient-to-br from-white to-rose-50/70 dark:border-rose-950/60 dark:from-stone-900 dark:to-rose-950/20",emerald:"border-emerald-100 bg-gradient-to-br from-white to-emerald-50/70 dark:border-emerald-950/60 dark:from-stone-900 dark:to-emerald-950/20"};return <Surface className={"border p-5 shadow-sm "+tones[tone]}><div className="flex items-center justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/80 text-stone-600 ring-1 ring-black/5 dark:bg-stone-900/60 dark:text-stone-300 dark:ring-white/10">{Icon&&<Icon size={19}/>}</span><span className="text-3xl font-black text-stone-900 dark:text-white">{value}</span></div><p className="mt-4 text-xs font-black uppercase tracking-wider text-stone-600 dark:text-stone-300">{label}</p><p className="mt-1 text-xs leading-5 text-stone-500 dark:text-stone-400">{text}</p></Surface>}
function ActionCard({icon,title,text,to}){return <Surface className="p-6"><div>{icon}</div><h2 className="mt-4 text-xl font-black dark:text-white">{title}</h2><p className="mt-2 text-sm text-stone-500">{text}</p><Link to={to} className="mt-4 inline-flex text-sm font-black text-emerald-600">Open workspace →</Link></Surface>}
