import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { AlertTriangle, Bot, ClipboardList, MapPin, RefreshCw, ShieldCheck, Siren } from "lucide-react";
import API from "../utils/api";
import Surface from "../components/ui/Surface.jsx";
import Button from "../components/ui/Button.jsx";
import EmptyState from "../components/ui/EmptyState.jsx";
import { CaseListSkeleton } from "../components/ui/LoadingState.jsx";
import { StatusBadge, PriorityBadge } from "../components/ui/Badge.jsx";

export default function AdminWorkspace(){
 const location=useLocation(); const [cases,setCases]=useState([]); const [junk,setJunk]=useState([]); const [loading,setLoading]=useState(true); const [acting,setActing]=useState(null); const view=location.pathname.split("/")[2]||"control";
 const load=useCallback(async()=>{setLoading(true);try{const [c,j]=await Promise.all([API.get("/cases"),API.get("/cases/admin/junk")]);setCases(Array.isArray(c.data)?c.data:[]);setJunk(Array.isArray(j.data)?j.data:[]);}catch{}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const counts=useMemo(()=>({total:cases.length,ai:cases.filter(c=>["PENDING_VALIDATION","PROCESSING_ANALYSIS"].includes(c.status)).length,available:cases.filter(c=>c.status==="VALIDATION_PASSED"&&!c.assigned_volunteer_id).length,active:cases.filter(c=>c.status==="IN_PROGRESS").length,resolved:cases.filter(c=>c.status==="RESOLVED").length}),[cases]);
 const verify=async(id)=>{setActing(id);try{await API.put("/cases/"+id+"/verify-junk",{approved:true});await load();}finally{setActing(null);}};
 if(view==="control") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-stone-900 to-emerald-950 p-6 text-white sm:p-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-300">Administrator · network overview</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Rescue Control Center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-300">See the whole network at a glance. Dedicated workspaces handle cases and AI review.</p></section><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Total",counts.total,"text-slate-600","bg-stone-100 dark:bg-stone-800"],["AI queue",counts.ai,"text-violet-600","bg-violet-50 dark:bg-violet-950/30"],["Available",counts.available,"text-amber-600","bg-amber-50 dark:bg-amber-950/30"],["Active",counts.active,"text-rose-600","bg-rose-50 dark:bg-rose-950/30"],["Resolved",counts.resolved,"text-emerald-600","bg-emerald-50 dark:bg-emerald-950/30"]].map(([l,v,c,bg])=><div key={l} className={"rounded-[1.35rem] border border-stone-200/80 p-4 shadow-sm dark:border-stone-800 "+bg}><div className="flex items-center justify-between"><span className={"text-2xl font-black "+c}>{v}</span><span className="h-2 w-2 rounded-full bg-current opacity-70"/></div><p className="mt-3 text-[11px] font-black uppercase tracking-[0.12em] text-stone-400">{l}</p></div>)}</section><section className="mt-8 grid gap-4 md:grid-cols-3"><ActionCard icon={<Siren className="text-rose-500"/>} title="Global cases" text="Open the full case inventory for administrative operations." to="/admin/cases"/><ActionCard icon={<Bot className="text-violet-600"/>} title="AI validation" text={junk.length+" flagged case(s) need human review."} to="/admin/ai-validation"/><ActionCard icon={<ShieldCheck className="text-emerald-600"/>} title="Verification" text="Review completed rescues awaiting sign-off." to="/verification"/></section></main>;
 if(view==="cases") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-rose-600">Global operations</p><h1 className="mt-1 text-3xl font-black dark:text-white">All Rescue Cases</h1><p className="mt-2 text-sm text-stone-500">Global case inventory for administrative operations.</p></div><button onClick={load} className="inline-flex items-center gap-2 text-xs font-bold text-stone-500"><RefreshCw size={14}/> Refresh</button></header>{loading?<CaseListSkeleton/>:<div className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{cases.map(c=><Link key={c.id} to={"/cases/"+c.id} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg dark:border-stone-800 dark:bg-stone-900"><div className="flex justify-between"><p className="text-xs font-black uppercase tracking-wider text-stone-400">Case #{c.id}</p><PriorityBadge priority={c.priority}/></div><h2 className="mt-3 text-lg font-black dark:text-white">{c.species||"Animal rescue"}</h2><p className="mt-1 text-sm text-stone-500">{c.manual_address||c.issue_description||"Location available"}</p><div className="mt-4"><StatusBadge status={c.status} friendly compact/></div></Link>)}</div>}</main>;
 return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><section className="rounded-3xl bg-gradient-to-br from-violet-950 via-slate-950 to-stone-950 p-6 text-white sm:p-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-300">AI operations</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">AI Validation Review</h1><p className="mt-2 max-w-2xl text-sm text-stone-300">Human review of cases the AI validation stage flagged. This workspace is intentionally separate from the global case inventory.</p></section><div className="mt-6">{loading?<CaseListSkeleton/>:junk.length===0?<Surface className="p-8"><EmptyState icon="🤖" title="AI review queue is clear" message="No AI-flagged cases currently require review."/></Surface>:<div className="grid gap-4 lg:grid-cols-2">{junk.map(c=><Surface key={c.id} className="overflow-hidden border-violet-100 bg-gradient-to-br from-white via-white to-violet-50/60 p-0 shadow-[0_14px_36px_rgba(124,58,237,0.12)] ring-1 ring-violet-100/70 dark:border-violet-950/60 dark:from-stone-900 dark:via-stone-900 dark:to-violet-950/10"><div className="flex items-center justify-between border-b border-violet-100 bg-violet-50/70 px-5 py-4 dark:border-violet-950/60 dark:bg-violet-950/20"><div><p className="text-xs font-black uppercase tracking-wider text-violet-500">Case #{c.id}</p><h2 className="mt-1 text-xl font-black dark:text-white">{c.species||"Reported animal"}</h2></div><div className="grid h-10 w-10 place-items-center rounded-2xl bg-amber-50 text-amber-500 ring-1 ring-amber-100 dark:bg-amber-950/40 dark:ring-amber-900"><AlertTriangle size={18}/></div></div><div className="p-5"><p className="mt-0 text-sm leading-6 text-stone-600 dark:text-stone-300">{c.issue_description||"No description supplied."}</p><p className="mt-3 text-xs text-stone-500"><MapPin size={13} className="mr-1 inline"/> {c.manual_address||"Location available in case detail"}</p><div className="mt-5 flex gap-2"><Button as={Link} to={"/cases/"+c.id} variant="secondary" className="flex-1">Review case</Button><Button disabled={acting===c.id} onClick={()=>verify(c.id)} className="flex-1">{acting===c.id?"Processing...":"Mark as valid"}</Button></div></div></Surface>)}</div>}</div></main>;
}
function ActionCard({icon,title,text,to}){return <Surface className="p-6"><div>{icon}</div><h2 className="mt-4 text-xl font-black dark:text-white">{title}</h2><p className="mt-2 text-sm text-stone-500">{text}</p><Link to={to} className="mt-4 inline-flex text-sm font-black text-emerald-600">Open workspace →</Link></Surface>}
