import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { AlertTriangle, Building2, MapPin, RefreshCw, ShieldCheck, Users, Siren } from "lucide-react";
import API from "../utils/api";
import { useAuth } from "../contexts/AuthContext.jsx";
import { useToast } from "../contexts/ToastContext.jsx";
import Surface from "../components/ui/Surface.jsx";
import Button from "../components/ui/Button.jsx";
import EmptyState from "../components/ui/EmptyState.jsx";
import { CaseListSkeleton } from "../components/ui/LoadingState.jsx";
import { StatusBadge, PriorityBadge } from "../components/ui/Badge.jsx";

export default function NGOWorkspace(){
 const {user}=useAuth(); const {showToast}=useToast(); const location=useLocation(); const [cases,setCases]=useState([]); const [verification,setVerification]=useState([]); const [loading,setLoading]=useState(true); const [dispatch,setDispatch]=useState(null); const [assigning,setAssigning]=useState(null);
 const view=location.pathname.split("/")[2]||"operations"; const hasJurisdiction=user?.jurisdiction_lat!==null&&user?.jurisdiction_lat!==undefined;
 const load=useCallback(async()=>{setLoading(true);try{const [c,v]=await Promise.all([API.get("/cases"),API.get("/cases/verification-queue")]);setCases(Array.isArray(c.data)?c.data:[]);setVerification(Array.isArray(v.data)?v.data:[]);}catch(e){showToast(e.response?.data?.error||"Unable to load NGO operations.","error");}finally{setLoading(false);}},[showToast]);
 useEffect(()=>{load();},[load]);
 const active=useMemo(()=>cases.filter(c=>!["RESOLVED","REJECTED_JUNK","CANCELLED"].includes(c.status)),[cases]); const available=useMemo(()=>cases.filter(c=>c.status==="VALIDATION_PASSED"&&!c.assigned_volunteer_id),[cases]); const inProgress=useMemo(()=>cases.filter(c=>c.status==="IN_PROGRESS"),[cases]);
 const openDispatcher=async(id)=>{try{const {data}=await API.get("/cases/"+id+"/nearby-volunteers");setDispatch({caseId:id,volunteers:Array.isArray(data.volunteers)?data.volunteers:[],radiusKm:data.searchRadiusKm||null});}catch(e){showToast(e.response?.data?.error||"Unable to find nearby volunteers.","error");}};
 const assign=async(v)=>{setAssigning(v.id);try{await API.put("/cases/"+dispatch.caseId+"/assign",{volunteerId:v.id});showToast("Volunteer assigned and notified.","success");setDispatch(null);await load();}catch(e){showToast(e.response?.data?.error||"Assignment failed.","error");}finally{setAssigning(null);}};
 if(view==="operations") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><section className="rounded-3xl bg-gradient-to-br from-emerald-950 via-stone-900 to-slate-950 p-6 text-white sm:p-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-300">NGO operations</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Coordinate the rescue network.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-300">Monitor your jurisdiction, dispatch volunteers, and keep verification moving.</p></section><section className="mt-6 grid gap-3 sm:grid-cols-4"><Metric icon={<Siren/>} value={active.length} label="Active queue"/><Metric icon={<AlertTriangle/>} value={available.length} label="Needs dispatch"/><Metric icon={<Users/>} value={inProgress.length} label="In rescue"/><Metric icon={<ShieldCheck/>} value={verification.length} label="Verification"/></section><section className="mt-8 grid gap-4 lg:grid-cols-2"><Surface className="border-rose-100 bg-gradient-to-br from-white to-rose-50/60 p-6 dark:border-rose-950/60 dark:from-stone-900 dark:to-rose-950/10"><p className="text-xs font-black uppercase tracking-wider text-rose-600">Dispatch</p><h2 className="mt-1 text-xl font-black dark:text-white">Cases needing a volunteer</h2><div className="mt-4 space-y-3">{available.slice(0,5).map(c=><div key={c.id} className="flex items-center justify-between gap-3 rounded-2xl bg-stone-50 p-4 dark:bg-stone-800"><div><p className="font-black dark:text-white">Case #{c.id} · {c.species||"Animal"}</p><p className="text-xs text-stone-400">{c.manual_address||"Location available"}</p></div><Button size="sm" onClick={()=>openDispatcher(c.id)}>Find volunteer</Button></div>)}{!available.length&&<p className="text-sm text-stone-500">No validated cases currently need dispatch.</p>}</div></Surface><Surface className="border-emerald-100 bg-gradient-to-br from-white to-emerald-50/50 p-6 dark:border-emerald-950/60 dark:from-stone-900 dark:to-emerald-950/10"><p className="text-xs font-black uppercase tracking-wider text-emerald-600">Jurisdiction</p><h2 className="mt-1 text-xl font-black dark:text-white">{hasJurisdiction?"Operating area configured":"Setup required"}</h2><p className="mt-2 text-sm text-stone-500">{hasJurisdiction?"Your case feed is restricted to your configured service radius.":"Configure your operating area in Profile before expecting a case feed."}</p><Link to="/profile" className="mt-4 inline-flex text-sm font-black text-emerald-600">Open profile →</Link></Surface></section>{dispatch&&<Dispatch dispatch={dispatch} assigning={assigning} onAssign={assign} onClose={()=>setDispatch(null)}/>}</main>;
 if(view==="cases") return <CaseQueue cases={cases} loading={loading} onRefresh={load}/>;
 if(view==="volunteers") return <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><header><p className="text-xs font-black uppercase tracking-[0.18em] text-sky-600">NGO dispatch</p><h1 className="mt-1 text-3xl font-black dark:text-white">Volunteer coordination</h1><p className="mt-2 max-w-2xl text-sm text-stone-500">Volunteers are exposed by the current backend in relation to a rescue case. Choose an eligible case to find nearby available volunteers.</p></header><div className="mt-6">{available.length?<div className="grid gap-3 sm:grid-cols-2">{available.map(c=><Surface key={c.id} className="p-5"><p className="text-xs font-black uppercase tracking-wider text-stone-400">Case #{c.id}</p><h2 className="mt-1 text-lg font-black dark:text-white">{c.species||"Animal rescue"}</h2><p className="mt-1 text-sm text-stone-500">{c.manual_address||"Location available"}</p><Button className="mt-5 w-full" onClick={()=>openDispatcher(c.id)}><Users size={16}/> Find nearby volunteers</Button></Surface>)}</div>:<Surface className="p-8"><EmptyState icon="🦺" title="No dispatch work right now" message="Validated unassigned cases will appear here."/></Surface>}</div>{dispatch&&<Dispatch dispatch={dispatch} assigning={assigning} onAssign={assign} onClose={()=>setDispatch(null)}/>}</main>;
 return <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><header><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-600">NGO verification</p><h1 className="mt-1 text-3xl font-black dark:text-white">Verification handoff</h1><p className="mt-2 text-sm text-stone-500">There are {verification.length} completion(s) awaiting sign-off.</p></header><div className="mt-6"><Button as={Link} to="/verification">Open verification queue</Button></div></main>;
}
function Metric({icon,value,label}){return <Surface className="p-5">{icon}<p className="mt-3 text-3xl font-black dark:text-white">{value}</p><p className="text-xs font-black uppercase tracking-wider text-stone-400">{label}</p></Surface>}
function CaseQueue({cases,loading,onRefresh}){return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Jurisdiction queue</p><h1 className="mt-1 text-3xl font-black dark:text-white">Rescue Cases</h1><p className="mt-2 text-sm text-stone-500">Cases visible to this NGO under its service-area rules.</p></div><button onClick={onRefresh} className="inline-flex items-center gap-2 text-xs font-bold text-stone-500"><RefreshCw size={14}/> Refresh</button></header>{loading?<CaseListSkeleton/>:<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cases.map(c=><Link key={c.id} to={"/cases/"+c.id} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg dark:border-stone-800 dark:bg-stone-900"><div className="flex justify-between"><p className="text-xs font-black uppercase tracking-wider text-stone-400">Case #{c.id}</p><PriorityBadge priority={c.priority}/></div><h2 className="mt-3 text-lg font-black dark:text-white">{c.species||"Animal rescue"}</h2><p className="mt-1 text-sm text-stone-500">{c.manual_address||c.issue_description||"Rescue case"}</p><div className="mt-4"><StatusBadge status={c.status} friendly compact/></div></Link>)}</div>}</main>}
function Dispatch({dispatch,assigning,onAssign,onClose}){return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/50 p-0 backdrop-blur-sm sm:items-center sm:p-4" onClick={onClose}><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-3xl bg-white p-5 shadow-2xl dark:bg-stone-900 sm:p-6" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-sky-600">Case #{dispatch.caseId}</p><h2 className="text-xl font-black dark:text-white">Nearby volunteers</h2></div><button onClick={onClose} className="text-stone-400">✕</button></div><div className="mt-5 space-y-3">{dispatch.volunteers.length?dispatch.volunteers.map(v=><div key={v.id} className="flex items-center justify-between rounded-2xl bg-stone-50 p-4 dark:bg-stone-800"><div><p className="font-black dark:text-white">{v.full_name||"Volunteer"}</p><p className="text-xs font-bold text-emerald-600">{Number(v.distance_km||0).toFixed(2)} km away</p></div><Button size="sm" disabled={assigning===v.id} onClick={()=>onAssign(v)}>{assigning===v.id?"Assigning...":"Assign"}</Button></div>):<p className="rounded-2xl bg-stone-50 p-5 text-sm text-stone-500">No eligible nearby volunteers right now.</p>}</div></div></div>}
