import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Activity, CheckCircle2, MapPin, RefreshCw, Search, Siren } from "lucide-react";
import API from "../utils/api";
import { useAuth } from "../contexts/AuthContext.jsx";
import { useToast } from "../contexts/ToastContext.jsx";
import useVolunteerPresence from "../hooks/useVolunteerPresence.js";
import AvailabilityToggle from "../components/AvailabilityToggle.jsx";
import Surface from "../components/ui/Surface.jsx";
import Button from "../components/ui/Button.jsx";
import EmptyState from "../components/ui/EmptyState.jsx";
import { CaseListSkeleton } from "../components/ui/LoadingState.jsx";
import { StatusBadge, PriorityBadge } from "../components/ui/Badge.jsx";

export default function VolunteerWorkspace() {
  const { user } = useAuth(); const { showToast } = useToast(); const location = useLocation(); const presence = useVolunteerPresence();
  const [cases,setCases]=useState([]); const [loading,setLoading]=useState(true); const [processing,setProcessing]=useState(null);
  const view = location.pathname.split("/")[2] || "hub";
  const load=useCallback(async()=>{setLoading(true);try{const {data}=await API.get("/cases");setCases(Array.isArray(data)?data:[]);}catch(e){showToast(e.response?.data?.error||"Unable to load rescue cases.","error");}finally{setLoading(false);}},[showToast]);
  useEffect(()=>{load();},[load]);
  const available=useMemo(()=>cases.filter(c=>c.status==="VALIDATION_PASSED"&&!c.assigned_volunteer_id),[cases]);
  const active=useMemo(()=>cases.filter(c=>String(c.assigned_volunteer_id)===String(user?.id)&&["IN_PROGRESS","RESCUE_COMPLETED"].includes(c.status)),[cases,user?.id]);
  const history=useMemo(()=>cases.filter(c=>String(c.assigned_volunteer_id)===String(user?.id)&&c.status==="RESOLVED"),[cases,user?.id]);
  const current=active.find(c=>c.status==="IN_PROGRESS");
  const claim=async(id)=>{setProcessing(id);try{await API.put("/cases/"+id+"/claim");await load();showToast("Rescue accepted.","success");}catch(e){showToast(e.response?.data?.error||"This case could not be claimed.","error");}finally{setProcessing(null);}};
  if(view==="hub") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-950 via-stone-900 to-slate-950 p-6 text-white sm:p-9"><div className="grid gap-8 lg:grid-cols-[1.4fr_.6fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-300">Field operations</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Ready for the next rescue?</h1><p className="mt-3 max-w-xl text-sm leading-6 text-stone-300">Stay available, respond to validated cases, and continue the rescue assigned to you.</p><div className="mt-6 flex flex-wrap gap-3"><Button as={Link} to="/volunteer/cases" className="bg-emerald-500 hover:bg-emerald-400"><Search size={16}/> Find rescues</Button>{current&&<Button as={Link} to={"/cases/"+current.id} variant="secondary" className="border-stone-700 bg-stone-800 text-white"><Activity size={16}/> Continue rescue</Button>}</div></div><div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur"><p className="text-xs font-bold uppercase tracking-wider text-stone-400">Field status</p><p className="mt-2 text-2xl font-black text-emerald-300">{current?"ON RESCUE":presence.status||"OFFLINE"}</p><div className="mt-5"><AvailabilityToggle status={presence.status} isUpdating={presence.isUpdating} error={presence.error} onChange={presence.setAvailability} onRescue={Boolean(current)}/></div></div></div></section>
    <section className="mt-6 grid gap-3 sm:grid-cols-3"><VolunteerMetric Icon={Search} value={available.length} label="Available rescues" tone="amber"/><VolunteerMetric Icon={Activity} value={active.length} label="Your active" tone="emerald"/><VolunteerMetric Icon={CheckCircle2} value={history.length} label="Verified history" tone="sky"/></section>
  </main>;
  const list=view==="cases"?available:view==="active"?active:history;
  const title=view==="cases"?"Available Rescue Cases":view==="active"?"Active Rescue":"Rescue History";
  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Volunteer workspace</p><h1 className="mt-1 text-3xl font-black dark:text-white">{title}</h1><p className="mt-2 text-sm text-stone-500">{view==="cases"?"Validated cases available to claim.":view==="active"?"Your current rescue assignment.":"Verified rescues you completed."}</p></div><button onClick={load} className="inline-flex items-center gap-2 text-xs font-bold text-stone-500"><RefreshCw size={14}/> Refresh</button></header>
    {view==="active"&&current&&<Surface className="mt-6 border-emerald-200 bg-emerald-50 p-6 dark:border-emerald-900 dark:bg-emerald-950/20"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Live assignment</p><h2 className="mt-1 text-2xl font-black dark:text-white">Case #{current.id} · {current.species||"Animal rescue"}</h2><p className="mt-2 text-sm text-stone-600"><MapPin size={14} className="mr-1 inline"/> {current.manual_address||"Location in case detail"}</p></div><Button as={Link} to={"/cases/"+current.id}><Activity size={16}/> Open case</Button></div></Surface>}
    <div className="mt-6">{loading?<CaseListSkeleton/>:list.length===0?<Surface className="p-8"><EmptyState icon={view==="cases"?"🦺":view==="active"?"🛟":"🏁"} title={view==="cases"?"No rescues available":view==="active"?"No active rescue":"No verified history"} message="This workspace updates from the rescue case API."/></Surface>:<div className="grid gap-3 lg:grid-cols-2">{list.map(item=><article key={item.id} className="rounded-[1.5rem] border border-stone-200/90 bg-white p-5 shadow-[0_10px_30px_rgba(28,25,23,0.06)] transition-all hover:-translate-y-1 hover:shadow-[0_16px_38px_rgba(28,25,23,0.10)] dark:border-stone-800 dark:bg-stone-900 dark:shadow-none"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-600 ring-1 ring-emerald-100 dark:bg-emerald-950/40 dark:ring-emerald-900"><Siren size={19}/></span><PriorityBadge priority={item.priority}/></div><p className="mt-4 text-xs font-black uppercase tracking-wider text-stone-400">Case #{item.id}</p><h2 className="mt-1 text-lg font-black dark:text-white">{item.species||"Animal rescue"}</h2><p className="mt-1 line-clamp-2 text-sm text-stone-500">{item.issue_description||item.manual_address||"Rescue case"}</p><div className="mt-4 flex items-center justify-between gap-3"><StatusBadge status={item.status} friendly compact/><div className="flex gap-2"><Button as={Link} to={"/cases/"+item.id} variant="secondary" size="sm">View</Button>{view==="cases"&&<Button size="sm" disabled={processing===item.id} onClick={()=>claim(item.id)}>{processing===item.id?"Accepting...":"Accept rescue"}</Button>}</div></div></article>)}</div>}</div>
  </main>;
}
